; Base rules
program = {import | definition | declaration | datatype} ;
identifier = (letter | '_'), {letter | digit | '_'}
letter = any Unicode letter
INDENT = [newline], <increase indentation>
DEDENT = [newline], <decrease indentation>
